CREATE TABLE IF NOT EXISTS `#__decaronotifications_notifications` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL,
  `external_key` varchar(191) DEFAULT NULL,
  `source_component` varchar(64) NOT NULL,
  `source_entity` varchar(64) DEFAULT NULL,
  `source_entity_id` varchar(128) DEFAULT NULL,
  `event_name` varchar(128) DEFAULT NULL,
  `event_version` varchar(16) DEFAULT NULL,
  `category` varchar(64) NOT NULL DEFAULT 'general',
  `priority` varchar(16) NOT NULL DEFAULT 'normal',
  `title` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `action_url` varchar(2048) DEFAULT NULL,
  `action_label` varchar(255) DEFAULT NULL,
  `scheduled_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `published` tinyint(1) NOT NULL DEFAULT 1,
  `params` mediumtext DEFAULT NULL,
  `created_by` int unsigned NOT NULL DEFAULT 0,
  `created` datetime NOT NULL,
  `modified_by` int unsigned NOT NULL DEFAULT 0,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_uuid` (`uuid`),
  UNIQUE KEY `idx_source_external` (`source_component`,`external_key`),
  KEY `idx_source` (`source_component`,`source_entity`,`source_entity_id`),
  KEY `idx_category` (`category`),
  KEY `idx_priority` (`priority`),
  KEY `idx_visibility` (`published`,`scheduled_at`,`expires_at`),
  KEY `idx_created` (`created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__decaronotifications_recipients` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `notification_id` int unsigned NOT NULL,
  `recipient_key` varchar(191) NOT NULL,
  `recipient_type` varchar(32) NOT NULL,
  `user_id` int unsigned DEFAULT NULL,
  `recipient_component` varchar(64) DEFAULT NULL,
  `recipient_entity` varchar(64) DEFAULT NULL,
  `recipient_entity_id` varchar(128) DEFAULT NULL,
  `read_at` datetime DEFAULT NULL,
  `archived_at` datetime DEFAULT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_recipient` (`notification_id`,`recipient_key`),
  KEY `idx_user_state` (`user_id`,`read_at`,`archived_at`),
  KEY `idx_entity_recipient` (`recipient_component`,`recipient_entity`,`recipient_entity_id`),
  KEY `idx_notification` (`notification_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__decaronotifications_preferences` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `recipient_key` varchar(191) NOT NULL,
  `category` varchar(64) NOT NULL DEFAULT '*',
  `channel` varchar(32) NOT NULL DEFAULT 'internal',
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `digest` varchar(16) NOT NULL DEFAULT 'immediate',
  `created` datetime NOT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_recipient_category_channel` (`recipient_key`,`category`,`channel`),
  KEY `idx_recipient_key` (`recipient_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__decaronotifications_deliveries` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `notification_id` int unsigned NOT NULL,
  `recipient_id` int unsigned NOT NULL,
  `channel` varchar(32) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'queued',
  `attempts` smallint unsigned NOT NULL DEFAULT 0,
  `last_attempt_at` datetime DEFAULT NULL,
  `delivered_at` datetime DEFAULT NULL,
  `provider` varchar(64) DEFAULT NULL,
  `external_id` varchar(191) DEFAULT NULL,
  `error_code` varchar(64) DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `created` datetime NOT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_delivery_unique` (`notification_id`,`recipient_id`,`channel`),
  KEY `idx_delivery_status` (`status`,`channel`),
  KEY `idx_recipient` (`recipient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
