<?php
defined('_JEXEC') or die;
use Joomla\CMS\Language\Text;
$badge = static function (bool $ok): string { $class = $ok ? 'bg-success' : 'bg-warning text-dark'; $label = $ok ? Text::_('JYES') : Text::_('JNO'); return '<span class="badge ' . $class . '">' . htmlspecialchars($label, ENT_QUOTES, 'UTF-8') . '</span>'; };
?>
<div class="xdecaro-scope">
  <div class="row g-3 mb-3">
    <div class="col-12 col-lg-6"><div class="card h-100"><div class="card-header"><strong><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_PRODUCT'); ?></strong></div><div class="card-body"><dl class="row mb-0">
      <dt class="col-sm-5"><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_NAME'); ?></dt><dd class="col-sm-7"><?php echo htmlspecialchars((string) ($this->product['name'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></dd>
      <dt class="col-sm-5"><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_VERSION'); ?></dt><dd class="col-sm-7"><span class="badge bg-primary"><?php echo htmlspecialchars((string) ($this->product['version'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></span></dd>
      <dt class="col-sm-5"><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_INSTALLED'); ?></dt><dd class="col-sm-7"><?php echo $badge((bool) ($this->product['installed'] ?? false)); ?></dd>
    </dl></div></div></div>
    <div class="col-12 col-lg-6"><div class="card h-100"><div class="card-header"><strong><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_ENVIRONMENT'); ?></strong></div><div class="card-body"><dl class="row mb-0">
      <dt class="col-sm-5">Joomla</dt><dd class="col-sm-7"><?php echo htmlspecialchars((string) ($this->environment['joomla'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></dd>
      <dt class="col-sm-5">PHP</dt><dd class="col-sm-7"><?php echo htmlspecialchars((string) ($this->environment['php'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></dd>
      <dt class="col-sm-5"><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_DATABASE'); ?></dt><dd class="col-sm-7"><?php echo htmlspecialchars((string) ($this->environment['database'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></dd>
    </dl></div></div></div>
  </div>
  <div class="row g-3 mb-3">
    <div class="col-12 col-lg-6"><div class="card h-100"><div class="card-header"><strong><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_INCLUDED'); ?></strong></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0 align-middle"><thead><tr><th><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_EXTENSION'); ?></th><th><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_VERSION'); ?></th><th><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_STATUS'); ?></th></tr></thead><tbody>
    <?php foreach ($this->includedExtensions as $extension) : ?><tr><td><?php echo htmlspecialchars((string) ($extension['label'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string) ($extension['version'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo $badge((bool) ($extension['installed'] ?? false) && (bool) ($extension['enabled'] ?? false)); ?></td></tr><?php endforeach; ?>
    </tbody></table></div></div></div></div>
    <div class="col-12 col-lg-6"><div class="card h-100"><div class="card-header"><strong><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_UPDATES'); ?></strong></div><div class="card-body"><dl class="row mb-0"><dt class="col-sm-5"><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_PACKAGE'); ?></dt><dd class="col-sm-7"><?php echo $badge((bool) ($this->updateInfo['package_installed'] ?? false)); ?></dd><dt class="col-sm-5"><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_VERSION'); ?></dt><dd class="col-sm-7"><?php echo htmlspecialchars((string) ($this->updateInfo['package_version'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></dd><dt class="col-sm-5"><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_FEED'); ?></dt><dd class="col-sm-7 text-break"><?php echo htmlspecialchars((string) ($this->updateInfo['feed'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></dd></dl></div></div></div>
  </div>
  <div class="card mb-3"><div class="card-header"><strong><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_CONNECTED'); ?></strong></div><div class="card-body"><?php if (!$this->connectedComponents) : ?><div class="text-body-secondary"><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_NO_CONNECTED'); ?></div><?php else : ?><div class="d-flex flex-wrap gap-2"><?php foreach ($this->connectedComponents as $component) : ?><span class="badge bg-secondary"><?php echo htmlspecialchars((string) ($component['element'] ?? ''), ENT_QUOTES, 'UTF-8'); ?><?php if (!empty($component['version'])) : ?> · <?php echo htmlspecialchars((string) $component['version'], ENT_QUOTES, 'UTF-8'); ?><?php endif; ?></span><?php endforeach; ?></div><?php endif; ?></div></div>
  <div class="card"><div class="card-header"><strong><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_DIAGNOSTICS'); ?></strong></div><div class="card-body"><div class="row g-3"><div class="col-12 col-lg-6"><h3 class="h6"><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_TABLES'); ?></h3><ul class="list-group"><?php foreach ((array) ($this->diagnostics['tables'] ?? []) as $table => $ok) : ?><li class="list-group-item d-flex justify-content-between align-items-center gap-3"><code><?php echo htmlspecialchars((string) $table, ENT_QUOTES, 'UTF-8'); ?></code><?php echo $badge((bool) $ok); ?></li><?php endforeach; ?></ul></div><div class="col-12 col-lg-6"><h3 class="h6"><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_SERVICES'); ?></h3><ul class="list-group"><li class="list-group-item d-flex justify-content-between align-items-center gap-3"><span>Xdecaro Core</span><?php echo $badge((bool) ($this->diagnostics['core_available'] ?? false)); ?></li><li class="list-group-item d-flex justify-content-between align-items-center gap-3"><span><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_TASK_PLUGIN'); ?></span><?php echo $badge((bool) ($this->diagnostics['scheduler_plugin'] ?? false)); ?></li><li class="list-group-item d-flex justify-content-between align-items-center gap-3"><span><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_EMAIL_PLUGIN'); ?></span><?php echo $badge((bool) ($this->diagnostics['email_plugin'] ?? false)); ?></li><li class="list-group-item d-flex justify-content-between align-items-center gap-3"><span><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_QUEUE_TASK'); ?></span><?php echo $badge((bool) ($this->diagnostics['queue_task'] ?? false)); ?></li><li class="list-group-item d-flex justify-content-between align-items-center gap-3"><span><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_MAINTENANCE_TASK'); ?></span><?php echo $badge((bool) ($this->diagnostics['maintenance_task'] ?? false)); ?></li></ul><h3 class="h6 mt-3"><?php echo Text::_('COM_XDECARONOTIFICATIONS_INFO_CHANNELS'); ?></h3><div class="d-flex flex-wrap gap-2"><?php foreach ((array) ($this->diagnostics['channels'] ?? []) as $channel) : ?><span class="badge bg-info text-dark"><?php echo htmlspecialchars((string) $channel, ENT_QUOTES, 'UTF-8'); ?></span><?php endforeach; ?></div></div></div></div></div>
</div>
